spring:
  datasource:
    url: jdbc:oracle:thin:@${DB_DESENV_SERVER:localhost}:${DB_DESENV_PORT:1521}:${DB_DESENV_NAME:desenv-spring-pj-motos}
    username: ${DB_DESENV_USERNAME:RM98641}
    password: ${DB_DESENV_PASSWORD:280504}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
